[package]
name = "tipb_helper"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tipb = { git = "https://github.com/iosmanthus/tipb.git",  branch = "mem-table-scan" }
codec = { path = "../codec" }
tidb_query_datatype = { path = "../tidb_query_datatype" }
