[package]
name = "tipb_helper"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tipb = { git = "https://github.com/crazycs520/tipb.git",  branch = "hackathon-exe" }
codec = { path = "../codec" }
tidb_query_datatype = { path = "../tidb_query_datatype" }
