[package]
name = "tidb_query_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "TiKV query engine data types"

[dependencies]
tipb = { git = "https://github.com/iosmanthus/tipb.git",  branch = "mem-table-scan" }
bitflags = "1.0"
num-traits = "0.2"
failure = "0.1"
tikv_alloc = { path = "../tikv_alloc" }
